M48
; DRILL file KiCad 10.0.6 date 2026-09-19T16:41:30
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-19T16:41:30-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.000
%
G90
G05
T1
X168.395Y-88.11
X168.395Y-93.89
T2
X140.21Y-108.75
X145.29Y-107.734
X145.29Y-109.766
T3
X130.0Y-80.0
X130.0Y-130.0
X170.0Y-80.0
X170.0Y-130.0
T4
X161.5Y-129.32
M30
